import { useEffect, useState } from 'react';
import { getDashboard } from '../api/client';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export default function DashboardPage({ onBack }) {
  const [dashboard, setDashboard] = useState(null);
  useEffect(() => { getDashboard().then(setDashboard).catch(() => setDashboard({ error: true })); }, []);
  if (!dashboard) return <main><button className="text-btn" onClick={onBack}>Back to intake</button><h1>Operations dashboard</h1><p>Loading metrics...</p></main>;
  if (dashboard.error) return <main><button className="text-btn" onClick={onBack}>Back to intake</button><h1>Operations dashboard</h1><p>Dashboard unavailable.</p></main>;
  const categoryData = Object.entries(dashboard.categories).map(([category, count]) => ({ category: category.replaceAll('-', ' '), count }));
  return <main><button className="text-btn" onClick={onBack}>Back to intake</button><div className="eyebrow">OPERATIONS / MEASUREMENT</div><h1>Support performance.</h1><section className="metrics"><div className="metric"><span>Total cases</span><strong>{dashboard.total_cases}</strong><small>All recorded cases</small></div><div className="metric"><span>Reviewed</span><strong>{dashboard.reviewed_cases}</strong><small>Human decisions</small></div><div className="metric"><span>Reuse rate</span><strong>{Math.round(dashboard.response_reuse_rate * 100)}%</strong><small>Playbook-grounded</small></div><div className="metric"><span>Time saved</span><strong>{dashboard.avg_minutes_saved}m</strong><small>Per assisted response</small></div></section><section className="panel page-panel"><div className="panel-heading"><div><span className="kicker">ISSUE MIX</span><h2>Cases by category</h2></div></div><div className="chart"><ResponsiveContainer width="100%" height={220}><BarChart data={categoryData} layout="vertical" margin={{ top: 4, right: 12, left: 8, bottom: 4 }}><CartesianGrid stroke="#2b3839" horizontal={false}/><XAxis type="number" allowDecimals={false} stroke="#8b9c9a"/><YAxis dataKey="category" type="category" width={120} stroke="#8b9c9a"/><Tooltip contentStyle={{ background: '#172123', border: '1px solid #2b3839', color: '#e9f1ef' }}/><Bar dataKey="count" fill="#9ff4c5" radius={[0, 2, 2, 0]}/></BarChart></ResponsiveContainer></div>{categoryData.map(({ category, count }) => <div className="stat-row" key={category}><b>{category}</b><span>{count}</span></div>)}</section><section className="panel page-panel"><div className="panel-heading"><div><span className="kicker">HUMAN REVIEW</span><h2>AI outcomes</h2></div></div>{Object.entries(dashboard.ai).map(([status, count]) => <div className="stat-row" key={status}><b>{status}</b><span>{count}</span></div>)}</section><section className="panel page-panel"><div className="panel-heading"><div><span className="kicker">DOCS GAPS</span><h2>Unresolved guidance</h2></div></div>{dashboard.docs_gaps?.length ? dashboard.docs_gaps.map((category) => <div className="stat-row" key={category}><b>{category.replaceAll('-', ' ')}</b><span>Needs playbook</span></div>) : <p className="muted">No documentation gaps detected.</p>}</section></main>;
}
