PLAYBOOKS = {
    "wallet-connection": {"title": "Wallet connection", "summary": "Confirm the wallet is on the intended Base network, then reconnect the dapp session.", "steps": ["Check chain ID 8453 for Mainnet or 84532 for Sepolia.", "Disconnect stale sessions and reconnect.", "Never request a seed phrase or private key."], "citation": "Wallet connection playbook"},
    "transaction-reverted": {"title": "Transaction reverted", "summary": "Use the receipt status and logs to identify the contract precondition that failed.", "steps": ["Confirm the receipt belongs to the selected Base network.", "Review gas used and emitted logs.", "Reproduce on Sepolia when possible."], "citation": "Failed transaction playbook"},
    "rpc-error": {"title": "RPC errors", "summary": "Treat timeouts and rate limits as endpoint reliability issues first.", "steps": ["Check endpoint and network selection.", "Retry with backoff.", "Avoid sending duplicate transactions after an ambiguous timeout."], "citation": "RPC errors playbook"},
    "bridge-delay": {"title": "Bridge delay", "summary": "Bridge messages can take time to prove and relay between L1 and L2.", "steps": ["Confirm the source transaction succeeded.", "Use the bridge status page.", "Keep the source hash for escalation."], "citation": "Bridge delay playbook"},
    "security": {"title": "Security report", "summary": "Preserve evidence and protect the reporter from further loss.", "steps": ["Never request secrets.", "Record addresses, hashes, URLs, and timestamps.", "Escalate through the security response path."], "citation": "Security response playbook"},
    "contract-deployment": {"title": "Contract deployment", "summary": "Confirm the deployment transaction and compiler settings before retrying.", "steps": ["Check the deployment receipt and deployed bytecode.", "Compare compiler version, optimizer settings, and constructor arguments.", "Reproduce on Base Sepolia when possible."], "citation": "Contract deployment playbook"},
    "contract-verification": {"title": "Contract verification", "summary": "Verification requires the exact source and compiler metadata used for deployment.", "steps": ["Select the correct Basescan network.", "Match compiler version, optimizer settings, and constructor arguments.", "Verify the deployed address has bytecode."], "citation": "Contract verification playbook"},
    "faucet": {"title": "Testnet faucet", "summary": "Base Sepolia test funds are for development and are not mainnet assets.", "steps": ["Confirm the wallet is on Base Sepolia.", "Use an official Base faucet.", "Never share a private key or seed phrase."], "citation": "Testnet faucet playbook"},
}
